version: '3.8'
services:
  genesis-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - genesis-db


  genesis-db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: k8s-project
      MYSQL_USER: root
      #MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

