apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: genesis-db
  name: genesis-db
spec:
  type: NodePort
  ports:
    - port: 33066
      targetPort: 3306
  selector:
    io.kompose.service: genesis-db
status:
  loadBalancer: {}
