apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: genesis-db
  name: genesis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: genesis-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: genesis-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: k8s-project
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
          image: mysql:5.7.22
          name: genesis-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: genesis-db-claim0
      restartPolicy: Always
      volumes:
        - name: genesis-db-claim0
          persistentVolumeClaim:
            claimName: genesis-db-claim0
status: {}
